#!/usr/bin/python
# -*- coding: UTF-8 -*-
"""Module docstring.


This serves as a long usage message.
"""

# Copyright (C) ullix
# 
# The following terms apply to all files associated
# with the software unless explicitly disclaimed in individual files.
# 
# The authors hereby grant permission to use, copy, modify, distribute,
# and license this software and its documentation for any purpose, provided
# that existing copyright notices are retained in all copies and that this
# notice is included verbatim in any distributions. No written agreement,
# license, or royalty fee is required for any of the authorized uses.
# Modifications to this software may be copyrighted by their authors
# and need not follow the licensing terms described here, provided that
# the new terms are clearly indicated on the first page of each file where
# they apply.
# 
# IN NO EVENT SHALL THE AUTHORS OR DISTRIBUTORS BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY
# DERIVATIVES THEREOF, EVEN IF THE AUTHORS HAVE BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# 
# THE AUTHORS AND DISTRIBUTORS SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.  THIS SOFTWARE
# IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE
# NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR
# MODIFICATIONS.


import os
import sys
import glob
import time
import usb.core
import usb.util
import Image
import ImageFont
import ImageDraw
import StringIO
import getopt
import struct
import random
import xml.dom.minidom as dom
import inspect


__author__ = "ullix"
__copyright__ = "Copyright 2011"
__credits__ = [""]
__license__ = "GPL"
__version__ = "0.0.1"
__maintainer__ = ""
__email__ = ""
__status__ = "Prototype"



exepath = "/home/ullix/projects/photoframe/python/"
debug       = False
verbose     = False



def lineno():
    """Return the current line number."""
    return inspect.currentframe().f_back.f_lineno


def show_user_info():
   """Show user and group ids, as actual and effective."""
    
   vprint( 'Effective User  :', os.geteuid())
   vprint( 'Effective Group :', os.getegid())
   vprint( 'Actual User     :', os.getuid(), 'Login user:', os.getlogin())
   vprint( 'Actual Group    :', os.getgid())
   vprint( 'Actual Groups   :', os.getgroups())
   return


def vprint(*args, **kwargs ):
    """Print args as a single line IF debug is true, or if dprint keyword is true."""

    forceprint = False
    for key in kwargs:
        if key == "forceprint":
            forceprint =kwargs[key]
        
    line = ''
    if debug or forceprint : 
        for arg in args:
            line += str(arg) +" "
        log = open(exepath + 'pyframe.log', 'a')    
        log.write(line + "\n")
        log.close() 
        print line
         

def write_jpg2frame(dev, pic):
    """Attach header to picture, pad with zeros if necessary, and send to frame"""

    ts = time.time()    # for timing the transfer

    # create header and stack before picture
    rawdata = b"\xa5\x5a\x18\x04" + struct.pack('<I', len(pic)) + b"\x48\x00\x00\x00" + pic
    
    # total transfers must be complete chunks of 16384  = 2 ^14. Complete by padding with zeros
    # for error picture an extra \x00 is required. Why ?
    pad = 16384 - (len(rawdata) % 16384) +1          
    tdata = rawdata + pad * b'\x00' 
    vprint("len of rdata is :", len(rawdata), ", len/16384.=", len(rawdata)/16384., ", pad=", pad, ", Len von data after padding=", len(tdata), "= 16384 *",len(tdata)/16384.)

    sum = 0
    errorflag = False
    endpoint = 0x02
    
    try:
        # Syntax: write(self, endpoint, data, interface = None, timeout = None):    
        sum = dev.write(endpoint, tdata )
    except:
        print "\nERROR: Writing jpg2frame failed with message:", sys.exc_info()
        #sys.exit()
        
    td = time.time() - ts 
    vprint("write_jpg2frame: total bytes written:%d, total chunks of 16384=%.5f, pic transfer only: Sec/pic:%.2f,  pic/sec:%.2f" % (sum, sum/16384., td , 1/td))
 
    return


def send_picture (infile, dev, counter = None):
    """Read a picture from filesystem, prepare and send to frame"""
    #print("sendpicture:", infile, "counter=", counter)
    
    try:
        image = Image.open(infile)
    except IOError as (errno, msg):
        # prepare error pic and send
        wimage = Image.new("RGB",(800,480), "Red")
        draw = ImageDraw.Draw(wimage)
        draw.text((2 , 10 ), "Error", font=pfont['big'], fill="Black")
        draw.text((10 , 200 ), str(msg) +":" , font=pfont['small'], fill="black")
        draw.text((10 , 240 ),  infile, font=pfont['small'], fill="Black")
        
        output = StringIO.StringIO()
        wimage.save(output, "JPEG", quality=95)
        pic  = output.getvalue()
        output.close()
        #vprint("len(pic) =", len(pic), "chunks of 16384:",len(pic)/16384.,"q=",90)
        write_jpg2frame(dev, pic)

        return 2

    vprint("\nimage as original is :",image.format, image.size, image.mode, infile)
    #vprint( time.strftime("%d.%m.%Y %H:%M"))
    
    # convert from Palette mode (e.g GIF) to RGB mode
    if image.mode == "P":
        image = image.convert("RGB")
        vprint("\nimage after conversion from P to RGB is :",image.format, image.size, image.mode, infile)
    
    w = image.size[0]
    h = image.size[1]
    wh = float(w) / float(h)
    if wh < 1  : 
        vprint("Tall format, adjust")
        simage = image.resize((int(480. * wh  ),480))   
        image = Image.new("RGB",(800,480), "black")
        image.paste(simage, (400 - simage.size[0]/2,0))
          
    if image.size != (800,480): 
        w = image.size[0]
        h = image.size[1]
        wh = float(w) / float(h)
        
        r = 800./480.
        #vprint("image w/h:", wh, "(frame 800/480=",r))
        
        # crop the image to match the aspect ratio of the frame to avoid distortion of the picture
        # unless there is only a less than 5% difference
        if (wh > r * 1.05 or wh < r * 0.95): 
            w_crop = w 
            h_crop = w_crop / r 
            
            if h_crop <= h:
                h_delta_top = int((h - h_crop) / 4)
                h_delta_bottom = int((h - h_crop) * 3 / 4)                
                w_delta = int((w - w_crop) / 2)
                image = image.crop((0 + w_delta, 0 + h_delta_top, w - w_delta, h - h_delta_bottom)) 
        
            vprint("image after cropping: ", image.format, image.size, image.mode)
        else:
            vprint("image was NOT cropped")    

        # image MUST be resized EXACTLY to 800x480 to fit on the photoframe, 
        # otherwise gibberish or nothing appears on frame
        image = image.resize((800,480))
        
        vprint("image after resizing: ",  image.format, image.size, image.mode)

    else:
        vprint("image NOT resized and NOT cropped")
        
    pname   = os.path.basename(infile)                                              # current picture name
    pfolder = os.path.dirname(infile).rpartition('/')[2]                            # current picture folder
    pname_width, pname_height = pfont['small'].getsize(pname)                       # size of picture name 
    #vprint("text_width, text_height",text_width, text_height)

    # add text to picture   
    draw = ImageDraw.Draw(image)
    draw.text((800 - pname_width - 2, pname_height - 20 ), pname, font=pfont['small'], fill="blue")   # pic name
    draw.text((2, pname_height - 20 ), pfolder, font=pfont['small'], fill="blue")                     # pic directory
    draw.text((380, 305), time.strftime("%H:%M"), font=pfont['time'], fill="gold")                    # current time
    if counter != None : 
        draw.text((30, 20), "#"+str(counter + 1), font=pfont['medium'], fill="yellow")                # counter
    
    q = 94 
    # one slide could not be transferred with q=95??? at 94, 93 it worked, and also at 96, 97, 98, 99
    # ??? why not at 95
    # pic is 2009-07%20Norwegen/imgp1785-m2.jpg
    limit = 23

    nl = "\n" # to make a NewLine in the log file when the first new quality needs to be recalculated
    flag = False
    #f = open('bigfile', 'w')

    while True:
        output = StringIO.StringIO()
        try:
            image.save(output, "JPEG", quality=q)
        except IOError as errno:
            print "=======================================IOERROR in Image.save:", errno
            nimage = image.convert("RGB") 
            nimage.save(output, "JPEG", quality=q)
            #sys.exit()

        pic  = output.getvalue()
        output.close()

        vprint("len(pic) =", len(pic), "chunks of 16384:",len(pic)/16384.,"q=",q)
        
        # in some 4000 photos, only 3 required a quality of 95 to stay under 23 chunks of 16384
        # none required a quality of 94 or less
        #    22 required 96
        #   124 required 97
        #  ~700 required 98
        #       so about 3000 could do with 99 
        # when the limit was 24, it failed with a  USBError('Operation timed out',) error after a few pictures!
        # conclusion: use limit of 23, and quality of 95, but still check for len of picture!
        
        # Test for length and write log
        if len(pic) > (16384 * limit) :
            flag = True
            vprint(nl + "   limit=" + str(limit) + " (" + str(16384 * limit) +"), " + infile + ", q=" + str(q) + ", len(pic)=" + str(len(pic)) + "\n", forceprint = True)
        else:
            if flag:
                vprint("OK " + "limit=" + str(limit) + " (" + str(16384 * limit) +"), " + infile + ", q=" + str(q) + ", len(pic)=" + str(len(pic)) + "\n", forceprint = True)
            break

        q -= 1
        nl = "" # reset new line
 
    write_jpg2frame(dev, pic)
    
    return 0    


def isPicture(file):
    """Return true if file is picture in one of the supported formats""" 
    return os.path.splitext(file)[1][1:].lower() in ['jpg', 'jpeg', 'gif', 'png', 'tif', 'tiff', 'bmp']
     

def getfiles(path):
    """
    Fills picture_list with all picture files in and below path.
    Each line in picture_list is absolute path and filename of a supported picture.
    """    
    global picture_list
    try:
        # dir_list has all files and directories in path
        # any directory is WITHOUT ending '/'
        dir_list = os.listdir(path)
    except:
        # path may not be a directory or permission error
        print "ERROR: in getfiles, picture_list:", picture_list
        picture_list = None
        return
        
    for line in dir_list:
        file = path + "/" + line
        if os.path.isdir(file):
            getfiles( file)                 # dig into subdirectory
        elif isPicture(file):
            picture_list.append(file)
        else:   
            # neither picture file nor directory; ignore 
            pass
    return

def getcatalogs():
    """Return a list of all available catalogs in the users default gthumb directory"""
    
    # default path for the gthumb catalogs of the logged in user
    gpath = os.environ['HOME'] + "/.local/share/gthumb/catalogs"

    cats = []   
    cat_list = []    
    try:
        # dir_list has all files and directories in path
        # directories are WITHOUT ending '/'
        dir_list = os.listdir(gpath)
    except:
        # path may not be a directory or permission error
        print "ERROR: in getcatalogs, gpath:", gpath
        return []
        
    # get only the directories     
    for line in dir_list:
        file = gpath + "/" + line
        #print file 
        if os.path.isdir(file):
            cats.append(file)
        else:   
            # not a directory; ignore 
            #print "not a directory:", file 
            pass

    # now get each catalog file from each directory
    for cat in cats:
        try:
            # dir_list has all files and directories in path
            # any directory is WITHOUT ending '/'
            dir_list = os.listdir(cat)
        except:
            # path may not be a directory or permission error
            print "ERROR: in getcatalogs, cat:", cat
            return []
    
        for line in dir_list:
            file = cat + "/" + line
            #print os.path.splitext(file)[1][1:]
            # append file only if it has catalog extension
            if os.path.splitext(file)[1][1:] == "catalog":
                cat_list.append(file)
    
    cat_list.sort() 

    if random_mode:
        random.shuffle(cat_list)
           
    return cat_list       


def getfiles_from_catalogue(catalogue): 
    
    d = [] 
    baum = dom.parse(catalogue)

    for eintrag in baum.firstChild.childNodes: 
        if eintrag.nodeName == "files": 
            for knoten in eintrag.childNodes: 
                if knoten.nodeName == "file":
                    # strip off initial 'file://' in uri
                    # and replace '%20' with ' ' (blank)
                    #print knoten.getAttribute("uri")
                    file = knoten.getAttribute("uri")[7:].replace("%20", " ")
                    #file.replace("%C3%B6", "ö")
                    #file.replace("%C3%BC", "ü")                    
                    if isPicture(file):
                        d.append(file) 
    
    return d 
      

def slide_show(picture_list, timer):
    """Show the pictures in picture_list in order of picture_list or randomly.
    Run indefinitely in random mode. Use timer setting for delay between pictures
    """
        
    lpl = len(picture_list)
    if lpl == 0:
        print "No pictures to show"
        return 1
    else:
        print "Number of pictures to show:",len(picture_list)
         
    i = -1
    counter = 0
    ts = time.time() 
    while True:
        for i, picture in enumerate(picture_list):
            if debug:
                send_picture (picture, dev, i  )
            else:
                send_picture (picture, dev)
                                
            counter +=1      
            td = time.time() - ts
            vprint("#%d    Pictures written: %d,    sec/pic: %.2f,  pic/sec: %.2f" %(counter, counter, td/counter, counter/td))
        
            time.sleep(timer)

    vprint("Length picture list:",len(picture_list))
    return


def get_fonts():
    """Return the predefined picture fonts"""

    fontpath        = "/usr/share/fonts/truetype/freefont/"
    font1           = "FreeSansBold.ttf"
    pfont = {}
    pfont['big']    = ImageFont.truetype(fontpath + font1, 120)
    pfont['medium'] = ImageFont.truetype(fontpath + font1,  70)
    pfont['small']  = ImageFont.truetype(fontpath + font1,  25)
    pfont['time']   = ImageFont.truetype(fontpath + font1, 160)
    
    return pfont
 

def get_known_devices():
    # to identify photo frames by USB Vendor and Product ID
    # listed as: Name, idVendor, idProduct, [width , height - in pixel if applicable] 
    #
    # Samsung SPF-87H in either mini monitor mode or mass storage mode
    SPF87H_MiniMon  = {'name':"SPF87H Mini Monitor", 'idVendor':0x04e8, 'idProduct':0x2034, 'width':800, 'height':480 }
    SPF87H_MassSto  = {'name':"SPF87H Mass Storage", 'idVendor':0x04e8, 'idProduct':0x2033}
    # Samsung SPF-107H (data from web reports - not tested)
    SPF107H_MiniMon  = {'name':"SPF107H Mini Monitor", 'idVendor':0x04e8, 'idProduct':0x2036, 'width':1024, 'height':600 }
    SPF107H_MassSto  = {'name':"SPF107H Mass Storage", 'idVendor':0x04e8, 'idProduct':0x2035}
    # Samsung SPF-83H (data from web reports - not tested)
    SPF107H_MiniMon  = {'name':"SPF107H Mini Monitor", 'idVendor':0x04e8, 'idProduct':0x200d, 'width':800, 'height':600 }
    SPF107H_MassSto  = {'name':"SPF107H Mass Storage", 'idVendor':0x04e8, 'idProduct':0x200c}
    #          
    # 4GB flash: 1e3d:2092
    BFLASH4GB       = {'name':"Flash Drive 4 GB", 'idVendor':0x1e3d, 'idProduct':0x2092}
             
    known_devices_list  = ( SPF87H_MiniMon, SPF87H_MassSto, SPF107H_MiniMon, SPF107H_MassSto, SPF107H_MiniMon, SPF107H_MassSto, BFLASH4GB )
    #vprint(known_devices_list)
    return known_devices_list


 
def main(argv=None):
    global debug, random_mode, pfont, picture_list, dev, log

    usage = """
    Usage:  pframe [Options] [Commands]
    
    Options:
        -h, --help          Show help
        -d, --debug         Print debug information. Default is not debug
        -v, --verbose       Be more verbose (not active yet)
        -V, --version       Show version
        -p, --picture=File  Show picture File (can be of type JPEG, GIF, PNG, TIF, and any size)
        -r, --random        Pictures will be shown randomly. Default is sequential
        -t, --timer=S       Set timer to S seconds. Default is 1 sec
        -s, --sort=asc|dsc  Sorting ascending or descending. Everything else is no sorting (=default)  
        
            --path=Path     Path to the start directory, from where pyframe will search for pictures. It will descend
                            into subdirectories. Path must end without '/'. Path cannot be used together with gthumb.
                            If gthumb is set, Path will be ignored.
            --gthumb=Cat    Show pictures from the gthumb catalogs. Cat defines, which catalog to show. If Cat is 'all',
                            then all will be shown. It suffices to specify only a part of the full catalog name,
                            like 'hawaii' to match with '2010 Hawaii vacation'.
        -k,  --key=Key      Key is message to show in pic
        
    Commands:
        init                Capture photo frame in Mini-Monitor mode
     
    """

    debug        = False
    verbose      = False
    random_mode  = False
    sorting      = False
    gthumb       = False
    picture      = False   
    keytext      = False 
    timer        = 1
    picture_list = []  
    

    # path must end WITHOUT '/' !    
    #path = "/home/mm/bilder/timeline/2009-11 Thanksgiving"
    #path = "/home/mm/bilder/timeline/2009-10 San Diego"
    #path = "/home/mm/bilder/timeline/2011-07-21 Madeira"
    path = "/home/mm/bilder/timeline"
    #path = "/home/mm/bilder"
    #path = "/home/mm"

    # path for the gthumb catalogues of the user running the script
    gpath = os.environ['HOME'] + "/.local/share/gthumb/catalogs"

        
    # optional argv allows to run main with your set of command line options
    if argv is None:
        argv = sys.argv
  
    # parse command line options
    try:
        opts, args = getopt.getopt(argv[1:], "hVdvrt:s:p:k:", ["help", "version", "picture=", "verbose", "debug", "random", "timer=", "sort=", "path=", "gthumb=", "key="])
        vprint("opt:", opts, "args:", args)
    except getopt.GetoptError, err :
        # print help information and exit:
        vprint(str(err), forceprint = True) # will print something like "option -a not recognized"
        vprint(usage, forceprint = True)
        return 2


    # processing options
    for opt, optval in opts:    
        if opt in ("-h", "--help"):
            print usage
            return 0
            
        elif opt in ("-V", "--Version"):
            print "Version:", __version__
            return 0   
                                   
        elif opt in ("-d", "--debug"):
            debug = True
                      
        elif opt in ("-v", "--verbose"):
            verbose = True
   
    if debug:
        vprint("\n"+ time.strftime("%d.%m.%Y %H:%M") + "~~~~~~~~~~~~~~~~~~~Begin~~~~~~~~~~~~~~~~~~~~~~~~~")
        vprint("sys.argv= %s" % sys.argv)
        vprint("Debug was set to True")
 
    if verbose:
        vprint("Verbose was set to True")    


    known_devices_list = get_known_devices()    
    if debug: find_devices (known_devices_list)
    
    # next 2 lines manually define which devices to use
    device0 = known_devices_list[0]
    device1 = known_devices_list[1]
    dev = init_device(device0, device1) 
    if dev is None:
        vprint("Could not find device, giving up")
        return 2
    
    pfont = get_fonts()

    # processing remaining options
    for opt, optval in opts:
        if opt in ("-d", "--debug", "-v", "--verbose"):
            pass # already handled above
     
        elif opt in ("-r", "--random"):
            random.seed()
            random_mode = True
            vprint( "Random mode was set to True")    
            
        elif opt in ("-t", "--timer"):
            timer = float(optval) 
            vprint( "Timer was set to %s sec" % optval )    
            
        elif opt in ("-s", "--sort"):
            optval = optval.lower()
            if optval  in ("asc", "dsc"):
                sorting = optval
            else:
                sorting = "none"
            vprint( "Sorting was set to '%s'" % sorting)    
            
        elif opt in ("-p", "--picture"):
            #default = False
            picture = optval
            if not os.path.isfile(picture):
                print "Picture '%s' is not a file" % picture
                return 1
            vprint("Picture was set to '%s'" % optval )
            
        elif opt in ("--path"):
            if optval[-1:] == "/":
                path = optval[:-1]
            else:
                path = optval
            if not os.path.exists(path):
                print "Path '%s' does not exist" % path
                return 1                
            if not os.access(path, os.R_OK):
                print "Path '%s' cannot be read" % path
                return 1    
            if not os.path.isdir(path):
                print "Path '%s' is not a directory" % path
                return 1                                   
            vprint("Path was set to %s" % path)           

        elif opt in ("--gthumb"):
            optval = optval.lower()
            cat_list = getcatalogs()
                      
            for cat in cat_list:
                if optval in cat.lower() or optval == "all":
                    vprint("catalogue:", cat)
                    picture_list += getfiles_from_catalogue(cat)
            gthumb = True
            vprint("Gthumb mode was set to true")  

        elif opt in ("-k", "--key"):
            keytext = optval
            # prepare error pic and send
            wimage = Image.new("RGB",(800,480), "Black")
            draw = ImageDraw.Draw(wimage)
            draw.text((250 , 10 ), keytext, font=pfont['big'], fill="#665")

            # ein Time updating fehlt noch            
            #draw.text((380, 305), time.strftime("%H:%M"), font=pfont['big'], fill="#550")   # current time
            
            keys = [
                    ("F1","1 Live"),
                    ("F2","WDR 2"),
                    ("F3","WDR 5"),
                    ("F4","SWR 3"),
                    ("F5","Bayern 2"),
                    ("F6","Bayern 3"),
                    ("F7","Bayern 5 aktuell"),
                    ("F8","Bayern 5 plus"),
                    ("F9","NDR 1"),
                    ("F10","NDR 2"),
                    ("F11","NDR 90,3"),
                    ("F12","KOIT 96.5"),
                    ("i","Info"),
                    ("k","Bilder-Kataloge "),
                    ("ESC","ausschalten")
                    ]
            
            tcolor = "gray"
            tfont  = pfont['small']
            draw.text((10, 10 ), "Win+", font=tfont, fill=tcolor)        
            for i, txt in enumerate(keys,1):
                #print i, txt
                draw.text((10, 10 + 28 * i ), txt[0], font=tfont, fill=tcolor)
                draw.text((80, 10 + 28 * i ), txt[1], font=tfont, fill=tcolor)                
            """
            keys = [("i","Info"),
                    ("k","Bilder-Kataloge ")
                    ]
 
            draw.text((350, 180 ), "Win+", font=tfont, fill=tcolor)        
            for i, txt in enumerate(keys,1):
                #print i, txt
                draw.text((350, 180 + 30 * i ), txt[0], font=tfont, fill=tcolor)
                draw.text((420, 180 + 30 * i ), txt[1], font=tfont, fill=tcolor)                
            """    
            output = StringIO.StringIO()
            wimage.save(output, "JPEG", quality=95)
            pic  = output.getvalue()
            output.close()
            write_jpg2frame(dev, pic)

            vprint("Keytext picture was produced with text: '%s'" % optval )
                                     
        else:
            print "Programming error 'unhandled option': %s" % opt    # programming error! opt is in getopt above, but not handled here
            return 1
 
    # processing arguments
    for arg in args:
        arg = arg.lower()
        vprint("processing arguments, arg:", arg) 
        if arg == "init":
            # create a welcome slide and send to frame, then exit
            wtext = "Welcome"
            wtext_width, wtext_height = pfont['big'].getsize(wtext)
            vprint("wtext: %s, wtext_width, wtext_height: %d, %d" % (wtext, wtext_width, wtext_height))

            wimage = Image.new("RGB",(800,480), "Chocolate")
            draw = ImageDraw.Draw(wimage)
            draw.text((400 - wtext_width/2 , 240 - wtext_height/2 ), wtext, font=pfont['big'], fill="gold")
            
            output = StringIO.StringIO()
            q = 90
            wimage.save(output, "JPEG", quality = q)
            pic  = output.getvalue()
            output.close()
            vprint("len(pic) =", len(pic), "chunks of 16384:",len(pic)/16384.,"q=", q)
            write_jpg2frame(dev, pic)
            return 0    # init ends here!
            
        else:
            #args_valid = False
            vprint("Invalid argument '%s' provided" % arg)
            
    
    # If neither picture, nor gthumb, nor keytext, 
    # then default to scan path for pictures
    if picture: 
            send_picture (picture, dev )

    elif gthumb:
        slide_show(picture_list, timer)
    
    elif keytext:
        pass    # already done above
                    
    else: 
        getfiles(path)  # fills variable picture_list as global variable
        
        if random_mode:
            random.shuffle(picture_list)
             
        if sorting == "asc":
            picture_list.sort(reverse=False)
        elif sorting == "dsc":
            picture_list.sort(reverse=True)
        else:
            # no sorting
            pass

        slide_show(picture_list, timer)

   
    vprint("finished with options and args...")

               
    return 0


def find_devices (devicelist):
    """Try to find ALL known devices on USB bus."""
    vprint("\nFind known devices:")
    for device in devicelist:
        if find_device(device) is not None :
            vprint("\tFound    :", device)
        else:
            vprint("\tNOT found:", device )
    vprint("..........")        
    return


def find_device(device):
    """Try to find device on USB bus."""
    return usb.core.find(idVendor=device['idVendor'], idProduct=device['idProduct'])    


def init_device(device0, device1):

    vprint("\nTrying to find device",device0['name'])
    dev = find_device(device0)
 
    if dev is not None:
        vprint("found it, trying to init it")
        r = frame_init(dev)
        vprint("Init completed, r=", r)
    else:
        print("Could not find", device0['name'], " -  Going to use Mass Storage mode")
        vprint("Trying to find device",device1['name'])
        dev = find_device(device1)
        if dev is not None:
            vprint("found it, trying to switch it")
            frame_switch(dev)
            ts = time.time()
            while True:
                dev = find_device(device0)
                if dev is not None:
                    vprint("switching successful") 
                    break
                elif time.time() - ts > 2:
                    vprint(True, "switching failed")
                    
            frame_init(dev)
        else:
            print(True, "Could not find either device:", device0['name'], ", ", device1['name'], "\n")
        
    return dev


   
def frame_init(dev): 
    # set the active configuration. With no arguments, the first configuration will be the active one
    # 
    # Configuration setting is insufficient to keep frame in Mini Monitor mode. It switches back 
    # even after some pictures have been transferred successfully
    # it may not be necessary at all (but it does not seem to do any harm)
    #dev.set_configuration()
   
    # releasing and claiming interface is not sufficient for keeping frame in Mini Monitor mode
    # (but is also doing no harm)
    #usb.util.release_interface(dev, 0)
    #usb.util.claim_interface(dev, 0)
    
    # Syntax: ctrl_transfer(self, bmRequestType, bRequest, wValue=0, wIndex=0, data_or_wLength = None, timeout = None):
    # this is the minimum required to keep the frame in Mini Monitor mode!!!
    dev.ctrl_transfer(0xc0, 4 )    
    
    return 0  # always return as ok although not tested
    

def frame_switch(dev):
    
    # dev.ctrl_transfer(0xc0, 4 ) # as used for init does not switch into Mini Monitor mode
    # but this message does:  
      
    try:
        dev.ctrl_transfer(0x00|0x80,  0x06, 0xfe, 0xfe, 0xfe )
    except:
        # switching results in much activity on the bus, device id is changed, 
        # nothing is returned, resulting in errors. simpler to ignore 
        pass
       
    # settling of the bus and frame takes about 0.42 sec
    # give it some extra time, but then still make sure it has settled
    time.sleep(1)
     
    return 0     
        

if __name__ == "__main__": 
    # exit code of main is used for sys.exit 
    sys.exit(main())
    

